[project]
name = "etlegacy"
authors = ["ET:Legacy Team"]
version = "0.0.0"
channels = [
    "conda-forge",
]

platforms = ["linux-64", "osx-64", "win-64"]

[tasks]

[dependencies]
"python" = "3.13.3.*"
"git" = "2.49.0.*"


[feature.validation.tasks]
check-changes = { cmd = ["python", "./misc/check-changes.py"] }
autoformat = { cmd = ["python", "./misc/autoformat.py"] }

[feature.validation.dependencies]
"uncrustify" = "0.78.1.*"
"black"      = "25.1.0.*"

[environments]
validation = ["validation"]
