//==========================================================================
//
// Character Animation Script     M U L T I P L A Y E R
//
// This defines the animations and events that might occur at different times
// for this character. State changes, and random behaviour during idle/alert
// states will look here for default behaviour, if that character doesn't have
// something specific in their scripts for that level.
//
//==========================================================================
// DEFINES
//
// These can be used to simplify the scripting, by defining replacement strings

// TODOS
// [X] Fix MP40 / machinegun backwards walk firing
// [X] Make Rifle Grenade disappear immediately on firing instead of on weapon switch
// [X] Make Rifle Grenade appear delayed when attaching
// [ ] Speed up scoping anim
// [ ] Fix/Improve Sniper rifle crouch idle / crouch-walk / run fire
// [X] Readd longer Dynamite raise
// [ ] Fix Rifle Firing (kinda all of them)
// [ ] Fix Rifle/GPG40 Running suddenly looks like K98
// [ ] Fix Scoped Rifles backwards walk
// [X] Fix 1P MP34 Firing jiggle (go back to 'master')
// [X] Fix binocing mid-air not putting on binocs ! :(
// [X] Fix rifle prone raise
// [ ] Fix both scoped & unscoped FG 42 prone fast fire
// [ ] Fix FG42 doing a stabby when shooting and running
// [ ] Fix FG42 backwards crouching
// [ ] Fix grenade throws
// [ ] Prolong grenade held throw animation (its too short when throwing from a hold)
// [ ] Fix prone grenade raise
// [ ] Fix prone grenade throw
// [X] Fix flamer jumps
// [ ] Fix Flamer Midair firing
// [ ] Fix flamer run firing shaking / fix like with prone
// [ ] Fix flamer stand firing shaking / fix like with prone
// [ ] Fix flamer crouch bk firing shaking / fix like with prone
// [ ] Fix flamer crouch idle firing shaking / fix like with prone
// [X] Fix flamer prone firing
// [X] Fix Flamethrower prone switching & firing
// [X] Fix pistol jumps
// [X] Fix pistol prone raise
// [X] Fix pistol attach timings
// [X] Add pistol prone fast reload
// [X] Fix pistol crouch firing
// [X] Add open door animation
// [O] Fix backwards run with Landmine
// [ ] Fix brass ejecting out of the head of a player 3P silenced pistol
// [X] Fix akimbo jump
// [ ] Reevaluate 'jump_1step_1h' (it's like a worse version of 'jump_1step_2h' ?)
// [/] Make MG42 in 1P pan vertically (bipod missing)
// [X] Fix proning and then immediately deploying MG42 producing a weird animation (was due to bipod anim match missing)
// [X] Fix all MG42 jumps, crouchs, etc.
// [ ] Fix mg42 brass ejecting out of head in 3P
// [X] Fix all Mortar Jumps
// [O] Hide Mortar when climbing?
// [X] Make Overheat color linearly shift from yellow to red
// [X] Only select class when clicking OK in Limbo
// [ ] Keep stationary MG42 rotation when leaving the stations MG42?
// [X] Show some 3P animation for deploying / undeploying MG bipod
// [X] Delay attaching/showing GPG40 / MG42 bipod to when animation finishes instead of immediately as it starts
// [X] Don't hide the MG42 gun so quickly e.g. when moving forward and then proning - now always showing MG42 when proning
// [X] Show different torso prone idle anim when proning with undeployed MG
// [ ] Fix MG42 firing despite overheating when standing/crouching (does stop when proning)
// [X] Reeval scoping while jumping/midair - especiall forward jumping currently is not canceled by scoping >:(
// [X] Fix walkback with Panzer
// [/] Reduce dead-body height (only for item collision?)
// [X] Fix mid-air switch from pliers-smg
// [ ] Improve GPG40 fire animation straight into normal rifle firing
// [X] Improve SMG idle firing - crouch firing
// [ ] Make 2 separate FG42 prone reloads
// [ ] Make 2 separate sten prone reloads
// [ ] Re-eval 3P syringe firing / missing reload
// [X] Fix the 'midair' movetype
// [X] Fix mid-air smg/rifle leg kicks while shooting jumpforward
// [/] Fix binocs disrupting running leg animation :(
// [/] Add animation for calling in firing-for-effect !?
// [ ] Fix Pistol disappearing earlier than the DROP animation finishes when switching to SMG and firing :(
// [ ] Fix noAmmoSound not playing for trying to select Syringe or Grenade that are out of ammo
// [ ] Fix fast switching from Dyn to Pliers
// [X] Re-eval allied grenade rifle attach and fire animation (looks a bit too quick for me again)
// [ ] Give airplanes a shadow O_O
// [ ] Give mortar_set a flash dlight and a flash
// [X] Fix pliers jump attacking
// [ ] Try to improve plier cycle-firing while jumping
// [ ] Fix gpg40 being held like normal rifle when running
// [ ] Do a double check over the climbing animations (still too fast)
// [ ] Make a HEAT shader for the tip of guns that overheat that gets more red as overheating increases
// [ ] New Icons for: Where to !? & Follow me! & Cover me! & Improve upscaled YES & All Clear
// [ ] Really reduce muzzle flashes
// [X] Change SMG run shooting back to running
// [ ] Fix tracers sometimes coming out of your face thirdperson, sometimes out of your muzzle
// [ ] Fix SMG forward jump shooting
// [ ] Fix Airplane Alpha (totall wrong)
// [ ] Bake shadows into Airplane model
// [ ] Fix standing on dynamite jiggle
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// [O] Pick a custom frame when corpses/bodies fly through the air (???)
// [ ] Fix flamethrower muzzle flame tip bugging out
// [ ] Add frame independent way of generating muzzle smoke and fix em all - (reuse covi smoke bomb implementation?)
// [ ] Auto Select Thompson or MP40 when available
// [X] Add cmd line arg to set window title
// [X] Add flag for playing firing animation only as long as being held down (like with pliers already) - for: mg42, smg - (repurposed: loop -1)
// [X] Render 3P overheat smoke for others
// [ ] Canonicalize ALL the animation names :)
// [x] https://github.com/etlegacy/etlegacy/commit/adf5f722981f7b445ff2afb36ee2deea3bd1fe25#r147530970

DEFINES

// weapons
set weapons knives         = Knife AND Ka-Bar
set weapons pistols        = Luger AND Colt AND Silenced Luger AND Silenced Colt
set weapons akimbo_pistols = Akimbo Luger AND Silenced Akimbo Luger AND Akimbo Colt AND Silenced Akimbo Colt
// set weapons machineguns    = MP 40 AND Thompson AND Sten gun AND Flamethrower AND panzerfaust AND bazooka AND Mobile MG 42 AND Mobile Browning AND MP34
set weapons machineguns    = MP 40 AND Thompson AND Sten gun AND MP34
set weapons rifles         = K43 Rifle AND gpg40 AND m1 garand AND M7 AND FG 42 Paratroop Rifle AND Scoped K43 Rifle AND K43 Rifle Scope AND Scoped M1 Garand AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope
set weapons rgrifles       = K43 Rifle AND m1 garand AND gpg40 AND m7
set weapons scopes         = K43 Rifle Scope AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope
set weapons heavymgs       = Mobile MG 42 AND Mobile Browning AND Mobile MG 42 Bipod AND Mobile Browning Bipod
set weapons mortars        = Granatwerfer AND Mortar
set weapons packs          = Ammo Pack AND Satchel Charge AND medicheal
set weapons stens          = Sten gun AND MP34

set weapons one_handed_weapons = Luger AND Colt AND Silenced Luger AND Silenced Colt
set weapons two_handed_weapons = MP 40 AND Thompson AND Sten gun AND flamethrower AND panzerfaust AND bazooka AND K43 Rifle AND gpg40 AND M7 AND m1 garand AND FG 42 Paratroop Rifle AND Scoped M1 Garand AND Mobile MG 42 AND Scoped K43 Rifle AND K43 Rifle Scope AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope AND Mobile Browning AND MP34

// broke off dynamite, since we never want to throw it overhand
set weapons throwables = pineapple AND grenade AND Smoke Bomb

// weapons that the player should not hold in front of themselves as if they
// could aim with them
set weapons aimless = knives AND throwables AND dynamite weapon AND smokeGrenade AND Binoculars AND Landmine AND none

set weapons all = Luger AND Colt AND Silenced Luger AND Silenced Colt AND Binoculars AND special AND Ammo Pack AND knives AND dynamite weapon AND pineapple AND grenade AND smokeGrenade AND Smoke Bomb AND Landmine AND Satchel Charge AND MP 40 AND Thompson AND Sten gun AND flamethrower AND panzerfaust AND bazooka AND Ammo Pack AND Medicheal AND gpg40 AND M7 AND m1 garand AND FG 42 Paratroop Rifle AND Scoped M1 Garand AND Satchel Charge AND Landmine AND Mobile MG 42 AND Scoped K43 Rifle AND K43 Rifle Scope AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope AND Mortar AND Mounted Mortar AND Satchel Charge AND Satchel Charge Detonator AND Mobile Browning AND Granatwerfer AND Mounted Granatwerfer AND MP34
set weapons all_one_handed_weapons = Luger AND Colt AND Silenced Luger AND Silenced Colt AND Binoculars AND special AND Ammo Pack AND knives AND dynamite weapon AND pineapple AND grenade AND smokeGrenade AND Smoke Bomb AND Landmine AND Satchel Charge
set weapons all_two_handed_weapons = MP 40 AND Thompson AND Sten gun AND flamethrower AND panzerfaust AND bazooka AND Ammo Pack AND Medicheal AND gpg40 AND M7 AND m1 garand AND FG 42 Paratroop Rifle AND Scoped M1 Garand AND Satchel Charge AND Landmine AND Mobile MG 42 AND Scoped K43 Rifle AND K43 Rifle Scope AND M1 Garand Scope AND FG 42 Paratroop Rifle Scope AND Mortar AND Mounted Mortar AND Satchel Charge AND Satchel Charge Detonator AND Mobile Browning AND Granatwerfer AND Mounted Granatwerfer AND MP34

// movetypes
set movetype moving = walk AND walkcr AND walkcrbk AND walkbk AND run AND runbk AND straferight AND strafeleft
set movetype crouching = idlecr AND walkcr AND walkcrbk
set movetype backstep = walkbk AND runbk AND walkcrbk
set movetype proning = idleprone AND prone AND pronebk

//==========================================================================
// ANIMATIONS
//
//	NOTE: scripts are chosen by first-come-first-serve basis. The first match
//	      found is the one used.
//
// FORMAT:
//
// state <state description>
// {
//		<movement type>
//		{
//			[default / <condition type> [<condition value>], ...]
//			{
//				<both/legs/torso> <animation> [sound <filename>]
//				<both/legs/torso> <animation> [sound <filename>]
//				...
//			}
//		}
//	}
//
//	LEGEND:
//
//	 NOTE: 'combat' is the only state used in Multiplayer, the rest are unused SP
//	       remnants and not used.
//	<state description>: relaxed, query, alert, combat
//
//	<movement type> (see 'animMoveTypesStr'):
//		dead
//		idle
//		idlecr
//		walk
//		walkbk
//		walkcr
//		walkcrbk
//		run
//		runbk
//		straferight
//		strafeleft
//		swim
//		swimbk
//		climbup
//		climbdown
//		idleprone
//		prone
//		pronebk
//		turnright
//		turnleft
//		fallen
//		radio
//		radiocr
//		radioprone
//		midair
//
//	<condition type> (see 'animConditionsStr'):
//		weapons
//		enemy_position
//		enemy_weapon
//		underwater
//		mounted
//		movetype
//		underhand
//		leaning
//		impact_point
//		crouching
//		stunned
//		firing
//		short_reaction
//		enemy_team
//		parachute
//		charging
//		secondlife
//		health_level
//		flailing_type
//		gen_bitflag
//		aistate
//		suicide
//
//	<condition value> (bool if unspecified):
//		weapons: <see weapon pickup names>
//		enemy_weapon: <see weapon pickup names>
//		underwater: <no values>
//		mounted: MG42
//		movetype: <see movement types>
//		position: behind, infront, right, left
//		underhand: <no values>
//		leaning: right, left
//		impact_point: head, chest, gut, groin, shoulder_right, shoulder_left, knee_right, knee_left
//		health_level: 1, 2, 3

ANIMATIONS

state combat
{

	dead
	{
		default
		{
			both dead_corpse
		}
	}

	midair
	{
		weapons rifles, movetype jumpforward
		{
			legs jump_1step_2h torso stand_srifle
			// legs jump_1step_2h torso midair_1step_rifles_2h
			// torso jump_1step_midair_2h
			// both jump_1step_fire_2h
			// legs jump_1step_2h torso jump_1step_2h
		}
		weapons binoculars, gen_bitflag zooming
		{
			torso stand_binoculars
		}
		weapons satchel charge detonator
		{
			NOOP
		}
		weapons scopes
		{
			torso stand_scoped_rifle
		}
		weapons mortars
		{
			torso e_mortar_stand
		}
		weapons one_handed_weapons
		{
			torso stand_pistolB
		}
		weapons bazooka
		{
			torso stand_rifle
		}
		weapons panzerfaust
		{
			torso stand_panzer
		}
		weapons heavymgs
		{
			torso stand_mobilemg42
		}
		weapons two_handed_weapons, movetype jumpforward
		{
			torso jump_1step_midair_2h
			// both jump_1step_2h
			// NOOP
			// torso jump_1step_2h
			// torso jump_1step_fire_2h
		}
		weapons two_handed_weapons
		{
			torso stand_machinegun
			// NOOP
		}
		weapons dynamite weapon
		{
			torso jump_1step_1h
		}
		weapons akimbo_pistols
		{
			torso stand_akimbo
		}
		weapons throwables, gen_bitflag holding
		{
			torso holding_grenadeA
			torso holding_grenadeB
		}
		default
		{
			torso jump_1step_1h
		}
		// weapons knives
		// {
		// 	torso stand_knife
		// }
		// weapons pistols
		// {
		// 	torso stand_pistolB
		// }
		// default
		// {
		// 	torso jump_1step_2h
		// }
	}

	idle
	{
		// weapons Flamethrower
		// {
		// 	// legs stand_panzer torso e_mortar_stand
		// 	both stand_machinegun
		// }
		weapons Mortar AND Granatwerfer
		{
			legs stand_panzer torso e_mortar_stand
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons Satchel Charge
		{
			both stand_medpack
		}
		weapons satchel charge detonator
		{
			legs stand_medpack torso satchel_remote_stand
		}
		mounted MG42, firing
		{
			both firing_mg42
		}
		mounted MG42
		{
			both stand_mg42
		}
		weapons Binoculars, gen_bitflag zooming
		{
			legs stand_grenade torso stand_binoculars
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both stand_knife
		}
		weapons Ammo Pack AND Landmine
		{
			both stand_medpack
		}
		weapons Satchel Charge
		{
			both stand_medpack
		}
		weapons medicheal
		{
			both stand_medpack
		}
		weapons special
		{
			both stand_knife
		}
		weapons throwables, gen_bitflag holding
		{
			both holding_grenadeA
			both holding_grenadeB
		}
		weapons throwables AND dynamite weapon
		{
			both stand_grenade
		}
		weapons knives
		{
			both stand_knife
		}
		weapons pistols, firing
		{
			legs firing_pistolB_1 torso stand_pistolB
			legs firing_pistolB_2 torso stand_pistolB
		}
		weapons pistols
		{
			both stand_pistolB
		}
		weapons akimbo_pistols, firing
		{
			legs firing_pistolB_1 torso stand_akimbo
			legs firing_pistolB_2 torso stand_akimbo
		}
		weapons akimbo_pistols
		{
			legs stand_pistolB torso stand_akimbo
		}
		weapons Scoped M1 Garand
		{
			both stand_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both stand_srifle
		}
		weapons K43 Rifle
		{
			both stand_srifle
		}
		weapons gpg40
		{
			legs stand_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs stand_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both stand_srifle
		}
		weapons Scoped K43 Rifle
		{
			both stand_srifle
		}
		weapons K43 Rifle Scope
		{
			both stand_rifle
		}
		weapons M1 Garand Scope
		{
			both stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			both stand_rifle
		}
		weapons bazooka
		{
			legs stand_panzer torso stand_rifle
		}
		weapons panzerfaust, firing
		{
			legs firing_panzer torso stand_panzer
		}
		weapons panzerfaust
		{
			both stand_panzer
		}
		weapons Mobile MG 42 AND Mobile Browning, firing
		{
			legs firing_machinegun torso firing_mobilemg42
		}
		weapons Mobile MG 42 AND Mobile Browning
		{
			legs stand_machinegun torso stand_mobilemg42
		}
		weapons machineguns, firing
		{
			legs firing_machinegun torso stand_machinegun
		}
		weapons machineguns AND Flamethrower
		{
			both stand_machinegun
		}
		weapons aimless
		{
			both stand_grenade
		}
	}

	idlecr
	{
		weapons heavymgs
		{
			legs alert_crchidle_2h torso stand_mobilemg42
		}
		weapons Mortar AND Granatwerfer
		{
			legs alert_crchidle_2h torso e_mortar_stand
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_crchidle_1h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_crchidle_2h torso satchel_remote_stand
		}
		weapons Binoculars, gen_bitflag zooming
		{
			legs alert_crchidle_1h torso stand_binoculars
		}
		weapons Syringe AND Adrenaline Syringe
		{
			legs alert_crchidle_1h torso stand_knife
		}
		weapons Ammo Pack
		{
			legs alert_crchidle_1h torso stand_medpack
		}
		weapons Satchel Charge
		{
			legs alert_crchidle_1h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_crchidle_1h torso stand_medpack
		}
		weapons special
		{
			both alert_crchidle_1h
		}
		weapons one_handed_weapons
		{
			legs alert_crchidle_1h torso stand_pistolB
		}
		weapons Scoped M1 Garand
		{
			both alert_crchidle_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_crchidle_srifle
		}
		weapons K43 Rifle
		{
			both alert_crchidle_srifle
		}
		weapons gpg40
		{
			legs alert_crchidle_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_crchidle_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_crchidle_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_crchidle_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_crchidle_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_crchidle_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_crchidle_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_crchidle_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_crchidle_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			legs alert_crchidle_2h torso stand_machinegun
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_crchidle_1h torso holding_grenadeA
			legs alert_crchidle_1h torso holding_grenadeB
		}
		weapons akimbo_pistols
		{
			legs alert_crchidle_1h torso stand_akimbo
		}
		weapons aimless
		{
			legs alert_crchidle_1h torso stand_grenade
		}
		default
		{
			both alert_crchidle_1h
		}
	}

	walk
	{
		weapons heavymgs
		{
			legs relaxed_walk_1h_1 torso stand_mobilemg42
		}
		weapons Mortar AND Granatwerfer
		{
			legs relaxed_walk_1h_1 torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs relaxed_walk_1h_1 torso stand_medpack
		}
		weapons satchel charge detonator
		{
			both satchel_remote_walk
			// legs relaxed_walk_1h_1 torso satchel_remote_stand
		}
		weapons Binoculars, gen_bitflag zooming
		{
			legs relaxed_walk_1h_1 torso stand_binoculars
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both relaxed_walk_1h_1
		}
		weapons Ammo Pack
		{
			legs relaxed_walk_1h_1 torso stand_medpack
		}
		weapons Satchel Charge
		{
			legs relaxed_walk_1h_1 torso stand_medpack
		}
		weapons medicheal
		{
			legs relaxed_walk_1h_1 torso stand_medpack
		}
		weapons throwables, gen_bitflag holding
		{
			legs relaxed_walk_1h_1 torso holding_grenadeA
			legs relaxed_walk_1h_1 torso holding_grenadeB
		}
		weapons one_handed_weapons
		{
			legs relaxed_walk_1h_1 torso stand_pistolB
		}
		weapons Scoped M1 Garand
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons K43 Rifle
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons gpg40
		{
			legs relaxed_walk_1h_1 torso stand_grenlauncher
		}
		weapons M7
		{
			legs relaxed_walk_1h_1 torso stand_grenlauncher
		}
		weapons m1 garand
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons Scoped K43 Rifle
		{
			legs relaxed_walk_1h_1 torso stand_srifle
		}
		weapons K43 Rifle Scope
		{
			legs relaxed_walk_1h_1 torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs relaxed_walk_1h_1 torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs relaxed_walk_1h_1 torso stand_rifle
		}
		weapons bazooka
		{
			legs relaxed_walk_1h_1 torso stand_rifle
		}
		weapons panzerfaust
		{
			legs relaxed_walk_1h_1 torso stand_panzer
		}
		weapons two_handed_weapons
		{
			legs relaxed_walk_1h_1 torso stand_machinegun
		}
		weapons akimbo_pistols
		{
			legs relaxed_walk_1h_1 torso stand_akimbo
		}
		weapons aimless
		{
			both relaxed_walk_1h_1
		}
		default
		{
			both relaxed_walk_1h_1
		}
	}

	walkbk
	{
		weapons heavymgs
		{
			legs relaxed_walk_1h_bk_1 torso stand_mobilemg42
		}
		weapons Mortar AND Granatwerfer
		{
			legs relaxed_walk_1h_bk_1 torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons one_handed_weapons
		{
			legs relaxed_walk_1h_bk_1 torso stand_pistolb
		}
		weapons Binoculars, gen_bitflag zooming
		{
			legs relaxed_walk_1h_bk_1 torso stand_binoculars
		}
		weapons Syringe AND Adrenaline Syringe
		{
			legs relaxed_walk_1h_bk_1 torso relaxed_walk_1h_1
		}
		weapons packs
		{
			legs relaxed_walk_1h_bk_1 torso stand_medpack
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_bk_1h torso holding_grenadeA
			legs alert_bk_1h torso holding_grenadeB
		}
		weapons Scoped M1 Garand
		{
			both alert_bk_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			// both alert_bk_srifle
			legs relaxed_walk_1h_bk_1 torso stand_srifle
		}
		weapons K43 Rifle
		{
			both alert_bk_srifle
		}
		weapons gpg40
		{
			legs alert_bk_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_bk_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_bk_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_bk_srifle
		}
		weapons K43 Rifle Scope
		{
			legs relaxed_walk_1h_bk_1 torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs relaxed_walk_1h_bk_1 torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons bazooka
		{
			// legs alert_bk_2h torso stand_rifle
			legs relaxed_walk_1h_bk_1 torso stand_rifle
		}
		weapons panzerfaust
		{
			// legs alert_bk_2h torso stand_panzer
			legs relaxed_walk_1h_bk_1 torso stand_panzer
		}
		weapons two_handed_weapons
		{
			legs relaxed_walk_1h_bk_1 torso stand_machinegun
			// both alert_bk_2h
		}
		weapons akimbo_pistols
		{
			legs alert_bk_2h torso stand_akimbo
		}
		weapons aimless
		{
			both relaxed_walk_1h_bk_1
		}
		default
		{
			both alert_bk_1h
		}
	}

	walkcr
	{
		weapons heavymgs
		{
			legs alert_crch_2h torso stand_mobilemg42
		}
		weapons Mortar AND Granatwerfer
		{
			legs alert_crch_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_crch_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_crch_2h torso satchel_remote_stand
		}
		weapons one_handed_weapons
		{
			both alert_crch_1h
		}
		weapons Binoculars, gen_bitflag zooming
		{
			legs alert_crch_1h torso stand_binoculars
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_crch_1h
		}
		weapons Ammo Pack
		{
			legs alert_crch_2h torso stand_medpack
		}
		weapons Satchel Charge
		{
			legs alert_crch_2h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_crch_2h torso stand_medpack
		}
		weapons special
		{
			both alert_crch_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_crch_1h torso holding_grenadeA
			legs alert_crch_1h torso holding_grenadeB
		}
		weapons throwables AND dynamite weapon
		{
			both alert_crch_1h
		}
		weapons Scoped M1 Garand
		{
			both alert_crch_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_crch_srifle
		}
		weapons K43 Rifle
		{
			both alert_crch_srifle
		}
		weapons gpg40
		{
			legs alert_crch_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_crch_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_crch_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_crch_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_crch_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_crch_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_crch_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_crch_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_crch_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_crch_2h
		}
		weapons akimbo_pistols
		{
			legs alert_crch_2h torso stand_akimbo
		}
		weapons aimless
		{
			both alert_crch_1h
		}
		default
		{
			both alert_crch_1h
		}
	}

	walkcrbk
	{
		weapons heavymgs
		{
			legs alert_crbk_2h torso stand_mobilemg42
		}
		weapons Mortar AND Granatwerfer
		{
			legs alert_crbk_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_crbk_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_crbk_2h torso satchel_remote_stand
		}
		weapons one_handed_weapons
		{
			both alert_crbk_1h
		}
		weapons Binoculars, gen_bitflag zooming
		{
			legs alert_crbk_1h torso stand_binoculars
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_crbk_1h
		}
		weapons Ammo Pack
		{
			legs alert_crbk_2h torso stand_medpack
		}
		weapons Satchel Charge
		{
			legs alert_crbk_2h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_crbk_2h torso stand_medpack
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_crbk_1h torso holding_grenadeA
			legs alert_crbk_1h torso holding_grenadeB
		}
		weapons Scoped M1 Garand
		{
			both alert_crbk_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_crbk_srifle
		}
		weapons K43 Rifle
		{
			both alert_crbk_srifle
		}
		weapons gpg40
		{
			legs alert_crbk_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_crbk_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_crbk_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_crbk_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_crbk_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_crbk_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_crbk_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_crbk_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_crbk_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_crbk_2h
			// both alert_crchbk_2h
		}
		weapons akimbo_pistols
		{
			legs alert_crbk_2h torso stand_akimbo
		}
		weapons aimless
		{
			both alert_crbk_1h
		}
		default
		{
			both alert_crbk_2h
		}
	}

	run
	{
		weapons heavymgs
		{
			legs alert_run_2h torso stand_mobilemg42
		}
		weapons Mortar AND Granatwerfer
		{
			legs alert_run_1h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons Satchel Charge
		{
			// both run_medpack
			legs alert_run_1h torso run_medpack
		}
		// weapons satchel charge
		// {
		// 	legs alert_run_1h torso stand_medpack
		// }
		weapons satchel charge detonator
		{
			legs alert_run_1h torso satchel_remote_stand
		}
		weapons Binoculars, gen_bitflag zooming
		{
			legs alert_run_no torso stand_binoculars
		}
		weapons Syringe AND Adrenaline Syringe
		{
			both alert_run_1h
		}
		weapons Ammo Pack
		{
			// both run_medpack
			legs alert_run_1h torso run_medpack
		}
		weapons medicheal
		{
			// both run_medpack
			legs alert_run_1h torso run_medpack
		}
		weapons special
		{
			both alert_run_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_run_no torso holding_grenadeA
			legs alert_run_no torso holding_grenadeB
		}
		weapons throwables AND dynamite weapon
		{
			both alert_run_no
		}
		weapons one_handed_weapons
		{
			legs alert_run_1h torso stand_pistolb
		}
		weapons rifles, movetype run AND swim
		{
			// legs alert_run_srifle torso stand_srifle
			legs alert_run_srifle torso alert_run_srifle
		}
		weapons Scoped M1 Garand
		{
			both alert_run_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_run_srifle
		}
		weapons K43 Rifle
		{
			legs alert_run_srifle torso stand_srifle
			// both alert_run_srifle
		}
		weapons gpg40
		{
			legs alert_run_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_run_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_run_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_run_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_run_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_run_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			both alert_run_2h
		}
		weapons akimbo_pistols
		{
			legs alert_run_2h torso stand_akimbo
		}
		weapons aimless
		{
			both alert_run_no
		}
		default
		{
			both alert_run_1h
		}
	}

	runbk
	{
		weapons heavymgs
		{
			legs alert_bk_2h torso stand_mobilemg42
		}
		weapons rifles
		{
			// both stand_srifle
			// legs alert_bk_srifle torso alert_bk_2h
			legs alert_bk_srifle torso stand_srifle
		}
		weapons Mortar AND Granatwerfer
		{
			legs alert_bk_2h torso e_mortar_run
		}
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			both mortar_deployed
		}
		weapons satchel charge
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons satchel charge detonator
		{
			legs alert_bk_2h torso satchel_remote_stand
		}
		weapons one_handed_weapons
		{
			legs alert_bk_1h torso stand_pistolb
		}
		weapons Binoculars, gen_bitflag zooming
		{
			legs alert_bk_1h torso stand_binoculars
		}
		weapons Syringe AND Adrenaline Syringe
		{
			legs alert_bk_1h
		}
		weapons Ammo Pack
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons Satchel Charge
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons medicheal
		{
			legs alert_bk_2h torso stand_medpack
		}
		weapons special
		{
			both alert_bk_1h
		}
		weapons throwables, gen_bitflag holding
		{
			legs alert_bk_1h torso holding_grenadeA
			legs alert_bk_1h torso holding_grenadeB
		}
		weapons throwables AND dynamite weapon
		{
			both alert_bk_1h
		}
		weapons Scoped M1 Garand
		{
			both alert_bk_srifle
		}
		weapons FG 42 Paratroop Rifle
		{
			both alert_bk_srifle
		}
		weapons K43 Rifle
		{
			both alert_bk_srifle
		}
		weapons gpg40
		{
			legs alert_bk_srifle torso stand_grenlauncher
		}
		weapons M7
		{
			legs alert_bk_srifle torso stand_grenlauncher
		}
		weapons m1 garand
		{
			both alert_bk_srifle
		}
		weapons Scoped K43 Rifle
		{
			both alert_bk_srifle
		}
		weapons K43 Rifle Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons M1 Garand Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons bazooka
		{
			legs alert_bk_2h torso stand_rifle
		}
		weapons panzerfaust
		{
			legs alert_bk_2h torso stand_panzer
		}
		weapons two_handed_weapons
		{
			// both alert_bk_2h
			legs alert_bk_srifle torso alert_bk_2h
		}
		weapons akimbo_pistols
		{
			legs alert_bk_2h torso stand_akimbo
		}
		//weapons Landmine
		//{
		//	both alert_run_no_bk
		//}
		weapons aimless
		{
			both alert_bk_1h
		}
		default
		{
			both alert_bk_2h
		}
	}

	swim
	{
		weapons binoculars, gen_bitflag zooming
		{
			torso stand_binoculars
		}
		weapons none
		{
			both e_swim_1h
		}
		weapons all_two_handed_weapons
		{
			both e_swim_2h
		}
		weapons all_one_handed_weapons
		{
			both e_swim_1h
		}
		default
		{
			both e_swim_1h
		}
	}

	swimbk
	{
		weapons binoculars, gen_bitflag zooming
		{
			torso stand_binoculars
		}
		weapons none
		{
			both e_swim_1h
		}
		weapons all_two_handed_weapons
		{
			both e_swim_2h
		}
		weapons all_one_handed_weapons
		{
			both e_swim_1h
		}
		default
		{
			both e_swim_1h
		}
	}

	climbup
	{
		weapons scopes
		{
			legs climb_up torso stand_rifle
		}
		weapons binoculars, gen_bitflag zooming
		{
			legs climb_up torso stand_binoculars
		}
		weapons throwables, gen_bitflag holding
		{
			legs climb_up torso holding_grenadeA
			legs climb_up torso holding_grenadeB
		}
		ladder_peek
  		{
			legs climb_up
  		}
		default
		{
			both climb_up
		}
	}

	climbdown
	{
		weapons scopes
		{
			legs climb_down torso stand_rifle
		}
		weapons binoculars, gen_bitflag zooming
		{
			legs climb_down torso stand_binoculars
		}
		weapons throwables, gen_bitflag holding
		{
			legs climb_down torso holding_grenadeA
			legs climb_down torso holding_grenadeB
		}
		ladder_peek
  		{
			legs climb_down
  		}
		default
		{
			both climb_down
		}
	}

	idleprone
	{
		weapons Mounted Mortar AND Mounted Granatwerfer
		{
			legs prone_legs torso mortar_deployed
		}
		weapons Mortar AND Granatwerfer
		{
			legs prone_legs torso e_prone_mortar_stand
		}
		weapons Satchel Charge
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons satchel charge detonator
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons medicheal
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons Mobile MG 42 Bipod AND Mobile Browning Bipod
		{
			legs prone_legs torso prone_mg42_idle
		}
		weapons Mobile MG 42 AND Mobile Browning
		{
			// legs prone_legs torso prone_mg42_idle
			legs prone_legs torso prone_mg_idle
		}
		weapons bazooka
		{
			// legs prone_legs torso e_prone_rifle_snipeidle
			legs prone_legs torso prone_baz_idle
		}
		weapons panzerfaust
		{
			legs prone_legs torso prone_panzer_idle
		}
		weapons machineguns
		{
			legs prone_legs torso prone_mg_idle
		}
		weapons binoculars, gen_bitflag zooming
		{
			legs prone_legs torso e_prone_binocs_lie
		}
		weapons binoculars
		{
			legs prone_legs torso e_prone_binocs_idle
		}
		weapons smokeGrenade
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons Ammo Pack
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons Landmine
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons medicheal
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons special
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons Syringe AND Adrenaline Syringe
		{
			legs prone_legs torso prone_poke_idle
		}
		weapons throwables, gen_bitflag holding
		{
			legs prone_legs torso holding_grenadeA
			legs prone_legs torso holding_grenadeB
		}
		weapons throwables AND dynamite weapon
		{
			legs prone_legs torso prone_grenade_idle
		}
		weapons knives
		{
			legs prone_legs torso prone_knife_idle
		}
		weapons pistols
		{
			legs prone_legs torso prone_pistol_idle
		}
		weapons akimbo_pistols
		{
			legs prone_legs torso e_prone_pistols_idle	// FIXME
		}
		weapons Scoped M1 Garand
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons FG 42 Paratroop Rifle
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons K43 Rifle
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons gpg40
		{
			legs prone_legs torso e_prone_rifle_altidle
		}
		weapons M7
		{
			legs prone_legs torso e_prone_rifle_altidle
		}
		weapons m1 garand
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons Scoped K43 Rifle
		{
			legs prone_legs torso prone_rifle_idle
		}
		weapons K43 Rifle Scope
		{
			legs prone_legs torso e_prone_rifle_snipeidle
		}
		weapons M1 Garand Scope
		{
			legs prone_legs torso e_prone_rifle_snipeidle
		}
		weapons FG 42 Paratroop Rifle Scope
		{
			legs prone_legs torso e_prone_rifle_snipeidle
		}
		weapons rifles
		{
			legs prone_legs torso prone_rifle_idle
		}
		default
		{
			legs prone_legs torso Prone_Pistol_idle
		}
	}

	prone
	{
		default
		{
			both prone_crawl
		}
	}

	pronebk
	{
		default
		{
			both prone_crawl_bk
		}
	}

	turnright
	{
		// - fixed movetype condition, so reenabled crouch
		// - nixing 'weapons machineguns' because we don't
		// want to just slide with any weapon; adding mounted MG42
		// so that we don't dance around in the tank
		movetype idlecr, NOT mounted MG42
		{
			legs turn_crch_R
		}
		movetype idle, NOT mounted MG42
		{
			legs turn_machinegun_R
		}
	}

	turnleft
	{
		// - fixed movetype condition, so reenabled crouch
		// - nixing 'weapons machineguns' because we don't
		// want to just slide with any weapon
		movetype idlecr, NOT mounted MG42
		{
			legs turn_crch_L
		}
		movetype idle, NOT mounted MG42
		{
			legs turn_machinegun_R
		}
	}

	fallen
	{
		default
		{
			both wounded_idle_1
		}
	}

	radio
	{
		default
		{
			both stand_radio
		}
	}

	radiocr
	{
		default
		{
			legs alert_crchidle_1h torso stand_radio
		}
	}

	radioprone
	{
		default
		{
			legs prone_legs torso prone_poke_idle
		}
	}

}

//==========================================================================
// EVENTS
//
// format:
//
// <event description>
// {
//		[default / <condition type> [<condition value>], ...]
//		{
//			<both/legs/torso> <animation> [sound <filename>]
//			<both/legs/torso> <animation> [sound <filename>]
//			...
//		}
// }
//
// LEGEND:
//
//	<event description>:
//		fireweapon
//		fireweapon2
//		fireweaponprone
//		fireweapon2prone
//		raiseweaponprone
//		reloadprone
//		raiseweapon
//		dropweapon
//		reload
//		jump
//		jumpbk
//		climbdismount
//		death
//		revive
//		nopower
//		pain
//		do_alt_weapon_mode
//		undo_alt_weapon_mode
//		do_alt_weapon_mode_prone
//		undo_alt_weapon_mode_prone
//
//	NOTE: for gameplay anims (weapons firing, reload, etc) that show no legs movement
//		only the torso should animation from here, leave the legs doing what their
//		locomotive anims want them to do

EVENTS

fireweapon
{
	mounted MG42
	{
		both firing_mg42
	}
	weapons Mounted Mortar AND Mounted Granatwerfer
	{
		torso mortar_fire
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso firing_mobilemg42
	}
	weapons Adrenaline Syringe
	{
		torso self_inject
	}
	weapons Satchel Charge
	{
		torso throw_satchel
	}
	// weapons Satchel Charge Detonator
	// {
	// 	torso satchel_remote_fire
	// }
	weapons packs AND Landmine
	{
		torso throw_underhand_instant
	}
	weapons special
	{
		torso firing_pliers
	}
	weapons Syringe
	{
		torso firing_syringe
	}
	weapons bazooka
	{
		// torso firing_bazooka
		torso firing_a_drop_bazooka
	}
	weapons panzerfaust
	{
		torso firing_panzer
	}
	weapons dynamite weapon
	{
		torso throw_underhand_dyn
	}
	// support overhand throws for airstrike tags
	weapons smokeGrenade, underhand
	{
		torso throw_underhand_instant
	}
	weapons smokeGrenade
	{
		torso firing_smoke_grenade
	}
	// support overhand throws for grenades
	weapons throwables, underhand
	{
		torso throw_underhand
		// torso throw_underhand_instant
	}
	weapons throwables
	{
		torso throw_overhand
	}
	weapons knives
	{
		torso firing_knife
	}
// PISTOLS
	// weapons pistols, movetype walkcrbk
	// {
	// 	torso firing_crbk_1h
	// }
	weapons pistols, movetype idlecr
	{
		// torso firing_crch_1h_idle
		torso firing_pistol
	}
	weapons pistols, movetype crouching
	{
		torso firing_crbk_1h
	}
	weapons pistols
	{
		// torso firing_pistolB_1
		torso firing_pistol
	}
	weapons akimbo_pistols
	{
		torso firing_akimbo
	}
	// weapons Flamethrower
	// {
	// 	// torso stand_rifle
	// 	torso alert_crchidle_1h
	// }
// MACHINEGUNS
	// weapons machineguns, movetype runbk
	// {
	// 	torso firing_alert_runbk_2h duration 50
	// }
	// weapons machineguns, movetype jumpforward
	// {
	// 	torso jump_1step_fire_2h
	// }
	weapons machineguns, movetype runbk
	{
		torso firing_alert_run_bk_2h
        // torso firing_machinegun
	}
	weapons machineguns, movetype jumpforward
	{
		// torso firing_alert_run_2h
        // torso firing_machinegun

		// torso jump_1step_2h
		// torso jump_1step_fire_2h
        torso firing_machinegun
	}
	weapons machineguns, movetype run AND swim
	{
		torso firing_alert_run_2h
        // torso firing_machinegun
	}
	weapons machineguns, movetype idlecr
	{
		torso firing_machinegun duration 50
	}
	// weapons machineguns, movetype walkcr AND walkcrbk
	weapons machineguns, movetype walkcrbk
	{
		torso firing_crbk_2h
        // torso firing_machinegun
	}
	weapons machineguns, movetype crouching
	{
		// torso firing_crch_2h duration 50
		torso firing_alert_crch_2h
	}
	// weapons machineguns, movetype crouching
	// {
	// 	// torso firing_machinegun duration 50
	// 	torso firing_alert_runbk_2h duration 50
	// }
	// weapons machineguns, movetype backstep AND swimbk
	// {
	// 	torso firing_alert_runbk_2h duration 50
	// }
	// weapons stens
	// {
        // torso firing_machinegun duration 50
	// 	// torso firing_machinegun duration 50
	// }
	weapons machineguns
	{
        torso firing_machinegun
		// torso firing_machinegun duration 50
	}
	// FG 42 Paratroop Rifle
	// weapons FG 42 Paratroop Rifle, movetype jumpforward
	// {
	// 	torso jump_1step_fire_2h
	// }
	// weapons FG 42 Paratroop Rifle, movetype walk AND turnleft AND turnright AND idlecr AND idle
	// {
	// 	torso firing_srifle
	// }
	weapons FG 42 Paratroop Rifle, movetype crouching
	{
		torso firing_crch_srifle
	}
	// weapons FG 42 Paratroop Rifle, movetype run AND swim
	// {
	// 	torso firing_run_srifle
	// }
	// weapons FG 42 Paratroop Rifle, movetype backstep AND swimbk
	// weapons FG 42 Paratroop Rifle, movetype backstep AND swimbk
	// {
	// 	torso firing_bk_srifle
	// }
	weapons FG 42 Paratroop Rifle
	{
		torso firing_fg42
	}

	weapons rifles, movetype run
	{
		torso fire_run_srifle
	}
// RIFLES (Scoped)
	weapons K43 Rifle Scope, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_rifle
	}
	weapons K43 Rifle Scope, movetype crouching
	{
		torso firing_crch_2h
	}
	weapons K43 Rifle Scope, movetype run AND swim
	{
		torso alert_run_2h
	}
	weapons K43 Rifle Scope, movetype backstep AND swimbk
	{
		torso firing_bk_2h
	}
	weapons K43 Rifle Scope
	{
		torso firing_rifle
	}
	weapons M1 Garand Scope
	{
		torso firing_rifle
	}
	weapons M1 Garand Scope, movetype crouching
	{
		torso firing_crch_2h
	}
	weapons M1 Garand Scope, movetype run AND swim
	{
		torso alert_run_2h
	}
	weapons M1 Garand Scope, movetype backstep AND swimbk
	{
		torso firing_bk_2h
	}
	weapons M1 Garand Scope
	{
		torso firing_rifle
	}
	weapons FG 42 Paratroop Rifle Scope, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_rifle
	}
	weapons FG 42 Paratroop Rifle Scope, movetype crouching
	{
		torso firing_crch_2h
	}
	weapons FG 42 Paratroop Rifle Scope, movetype run AND swim
	{
		torso alert_run_2h
	}
	weapons FG 42 Paratroop Rifle Scope, movetype backstep AND swimbk
	{
		torso firing_bk_2h
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso firing_rifle
	}
// RIFLES
	// K43
	weapons K43 Rifle, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_srifle
		// NOOP
	}
	weapons K43 Rifle, movetype crouching
	{
		// torso firing_srifle
		torso firing_crch_srifle
		// NOOP
	}
	weapons K43 Rifle, movetype run AND swim
	{
		torso firing_run_srifle
		// torso firing_srifle
		// torso firing_srifle
		// NOOP
	}
	weapons K43 Rifle, movetype backstep AND swimbk
	{
		// torso firing_bk_srifle
		NOOP
	}
	weapons K43 Rifle
	{
		// torso firing_srifle
		NOOP
	}
	// GPG40
	weapons gpg40, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_grenlauncher
	}
	weapons gpg40, movetype crouching
	{
		torso firing_grenlauncher
	}
	weapons gpg40, movetype run AND swim
	{
		torso firing_grenlauncher
	}
	weapons gpg40, movetype backstep AND swimbk
	{
		torso firing_grenlauncher
	}
	weapons gpg40
	{
		torso firing_grenlauncher
	}
	// M1 Garand
	weapons m1 garand, movetype walk
	{
		torso firing_srifle
	}
	weapons m1 garand, movetype crouching
	{
		torso firing_crch_srifle
	}
	weapons m1 garand, movetype run AND swim
	{
		// torso firing_srifle
		NOOP
		// torso firing_run_srifle
	}
	weapons m1 garand, movetype backstep AND swimbk
	{
		torso firing_bk_srifle
	}
	weapons m1 garand
	{
		torso firing_srifle
	}
	// M7
	weapons M7, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_grenlauncher
	}
	weapons M7, movetype crouching
	{
		torso firing_grenlauncher
	}
	weapons M7, movetype run AND swim
	{
		torso firing_grenlauncher
	}
	weapons M7, movetype backstep AND swimbk
	{
		torso firing_grenlauncher
	}
	weapons M7
	{
		torso firing_grenlauncher
	}
	// Scoped K43 Rifle
	weapons Scoped K43 Rifle, movetype walk AND turnleft AND turnright AND idlecr AND idle
	{
		torso firing_srifle
	}
	weapons Scoped K43 Rifle, movetype crouching
	{
		torso firing_crch_srifle
	}
	weapons Scoped K43 Rifle, movetype run AND swim
	{
		torso firing_run_srifle
	}
	weapons Scoped K43 Rifle, movetype backstep AND swimbk
	{
		torso firing_bk_srifle
	}
	weapons Scoped K43 Rifle
	{
		torso firing_srifle
	}
	// Scoped M1 Garand
	weapons Scoped M1 Garand, movetype walk
	{
		torso firing_srifle
	}
	weapons Scoped M1 Garand, movetype crouching
	{
		torso firing_crch_srifle
	}
	weapons Scoped M1 Garand, movetype run AND swim
	{
		torso firing_run_srifle
	}
	weapons Scoped M1 Garand, movetype backstep AND swimbk
	{
		torso firing_bk_srifle
	}
	weapons Scoped M1 Garand
	{
		torso firing_srifle
	}
	weapons rifles, movetype run AND swim
	{
		torso firing_srifle
		//torso firing_run_srifle
		// torso firing_srifle
		// NOOP
	}
}

// zoomin
// {
// 	weapons binoculars
// 	{
// 		torso raise_binoculars
// 	}
// }

fireweapon2
{
	weapons akimbo_pistols
	{
		torso firing_akimbo2
	}
}

fireweaponprone
{
	weapons Mobile MG 42 AND Mobile Browning
	{
		// torso prone_mg42_fire
		torso prone_mg_fire
	}
	weapons Mobile MG 42 Bipod AND Mobile Browning Bipod
	{
		torso prone_mg42_fire
	}
	weapons Adrenaline Syringe
	{
		torso self_inject
	}
	weapons Satchel Charge
	{
		torso prone_grenade_fire
	}
	// weapons Satchel Charge Detonator
	// {
	// 	torso prone_poke_fire
	// }
	weapons packs AND Landmine
	{
		torso prone_grenade_fire
	}
	weapons special
	{
		torso prone_poke_fire
	}
	weapons Syringe
	{
		torso prone_syringe_attack
	}
	weapons bazooka
	{
		torso e_prone_rifle_snipefire
	}
	weapons panzerfaust
	{
		torso prone_panzer_idle
	}
	weapons throwables AND dynamite weapon
	{
		torso prone_grenade_fire
	}
	weapons smokeGrenade
	{
		torso prone_grenade_fire
	}
	weapons knives
	{
		torso prone_knife_attack
	}
	weapons flamethrower
	{
		torso prone_flamethrower_fire
	}
// PISTOLS
	weapons pistols
	{
		torso prone_pistol_fire
	}
	weapons akimbo_pistols
	{
		torso e_prone_pistols_fire
	}
// MACHINEGUNS
	weapons machineguns
	{
		torso prone_mg_fire
	}
// RIFLES (Scoped)
	weapons scopes
	{
		torso e_prone_rifle_snipefire
	}
// RIFLES
	weapons K43 Rifle
	{
		torso prone_rifle_fire
	}
	weapons gpg40
	{
		torso e_prone_rifle_fire
	}
	weapons m1 garand
	{
		torso prone_rifle_fire
	}
	weapons M7
	{
		torso e_prone_rifle_fire
	}
	weapons FG 42 Paratroop Rifle
	{
		torso prone_rifle_fire
	}
	weapons Scoped K43 Rifle
	{
		torso prone_rifle_fire
	}
	weapons Scoped M1 Garand
	{
		torso prone_rifle_fire
	}
}

fireweapon2prone
{
	weapons akimbo_pistols
	{
		torso e_prone_pistols_fire2
	}
}

raiseweaponprone
{
	weapons Mortar AND Granatwerfer
	{
		torso e_prone_mortar_raise
	}
	weapons binoculars
	{
		torso e_prone_binocs_rase
	}
	weapons satchel charge
	{
		torso prone_grenade_switch
	}
	weapons satchel charge detonator
	{
		torso prone_poke_switch
	}
	weapons smokeGrenade
	{
		torso prone_grenade_switch
	}
	weapons Ammo Pack
	{
		torso prone_grenade_switch
	}
	weapons Landmine
	{
		torso prone_grenade_switch
	}
	weapons Satchel Charge
	{
		torso prone_grenade_switch
	}
	weapons medicheal
	{
		torso prone_poke_switch
	}
	weapons special
	{
		torso prone_poke_switch
	}
	weapons Syringe AND Adrenaline Syringe
	{
		torso prone_poke_switch
	}
	weapons bazooka
	{
		// torso prone_rifle_switch
		torso prone_baz_raise
	}
	weapons panzerfaust
	{
		torso prone_panzer_raise
	}
	weapons throwables AND dynamite weapon
	{
		torso prone_grenade_switch
	}
	weapons knives
	{
		torso prone_knife_switch
	}
	weapons pistols
	{
		torso e_prone_pistol_switch
	}
	weapons akimbo_pistols
	{
		torso e_prone_pistols_switch
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso prone_mg42_switch
	}
	weapons machineguns
	{
		torso prone_mg_switch
	}
// RIFLES
	weapons Scoped M1 Garand
	{
		torso prone_rifle_switch
	}
	weapons FG 42 Paratroop Rifle
	{
		torso prone_rifle_switch
	}
	weapons K43 Rifle
	{
		torso prone_rifle_switch
	}
	weapons gpg40
	{
		torso e_prone_rifle_altfire
	}
	weapons M7
	{
		torso e_prone_rifle_altfire
	}
	weapons m1 garand
	{
		torso prone_rifle_switch
	}
	weapons Scoped K43 Rifle
	{
		torso prone_rifle_switch
	}
	weapons K43 Rifle Scope
	{
		torso e_prone_rifle_snipe
	}
	weapons M1 Garand Scope
	{
		torso e_prone_rifle_snipe
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso e_prone_rifle_snipe
	}
}

reloadprone
{
	weapons smokeGrenade
	{
		torso prone_grenade_switch
	}
	weapons Ammo Pack
	{
		torso prone_grenade_switch
	}
	weapons Landmine
	{
		torso prone_grenade_switch
	}
	weapons Satchel Charge
	{
		torso prone_grenade_switch
	}
	weapons medicheal
	{
		torso prone_poke_switch
	}
	weapons special
	{
		torso prone_poke_switch
	}
	weapons throwables AND dynamite weapon
	{
		torso prone_grenade_switch
	}
	weapons pistols, fast_reload
	{
		torso prone_pistol_freload
	}
	weapons pistols
	{
		torso prone_pistol_reload
	}
	weapons akimbo_pistols
	{
		torso e_prone_pistols_reload
	}
	weapons heavymgs
	{
		torso prone_mg42_reload
	}
	weapons machineguns, fast_reload
	{
		torso prone_mg_reload_fast
	}
	weapons machineguns
	{
		torso prone_mg_reload
	}
// RIFLES
	weapons Scoped M1 Garand
	{
		torso prone_rifle_reload
	}
	weapons FG 42 Paratroop Rifle
	{
		torso prone_rifle_reload
	}
	weapons K43 Rifle
	{
		torso prone_rifle_reload
	}
	weapons gpg40
	{
		NOOP
	}
	weapons M7
	{
		NOOP
	}
	// weapons gpg40
	// {
	// 	torso e_prone_rifle_attach
	// }
	// weapons M7
	// {
	// 	torso e_prone_rifle_attach
	// }
	weapons m1 garand
	{
		torso prone_rifle_reload
	}
	weapons Scoped K43 Rifle
	{
		torso prone_rifle_reload
	}
	weapons K43 Rifle Scope
	{
		torso prone_rifle_reload
	}
	weapons M1 Garand Scope
	{
		torso prone_rifle_reload
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso prone_rifle_reload
	}
}

raiseweapon
{
	weapons Mortar AND Granatwerfer
	{
		torso e_mortar_raise
	}
	weapons satchel charge
	{
		torso raise_satchel
	}
	// weapons satchel charge detonator
	// {
	// 	torso satchel_remote_raise
	// }
	weapons smokeGrenade AND binoculars
	{
		torso raise_grenade
	}
	weapons Syringe AND Adrenaline Syringe
	{
		NOOP
	}
	weapons Landmine
	{
		torso raise_grenade
	}
	weapons packs
	{
		torso raise_medpack
	}
	weapons special
	{
		torso raise_knife
	}
	weapons bazooka
	{
		torso raise_bazooka
	}
	weapons panzerfaust
	{
		torso raise_panzer
	}
	weapons pistols
	{
		torso raise_pistolA
	}
	weapons akimbo_pistols
	{
		torso raise_akimbo
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso raise_mobilemg42
	}
	weapons flamethrower
	{
		torso raise_flamethrower
	}
	weapons machineguns
	{
		torso raise_machinegun
	}
// RIFLES
	weapons Scoped M1 Garand
	{
		torso raise_machinegun
	}
	weapons FG 42 Paratroop Rifle
	{
		torso raise_machinegun
	}
	weapons K43 Rifle
	{
		torso raise_machinegun
	}
	weapons gpg40
	{
		torso raise_grenlauncher
	}
	weapons M7
	{
		torso raise_grenlauncher
	}
	weapons m1 garand
	{
		torso raise_machinegun
	}
	weapons Scoped K43 Rifle
	{
		torso raise_machinegun
	}
	weapons K43 Rifle Scope
	{
		torso raise_sniper
	}
	weapons M1 Garand Scope
	{
		torso raise_sniper
	}
	weapons dynamite weapon
	{
		torso raise_dynamite
	}
	weapons aimless
	{
		torso raise_grenade
	}
	weapons FG 42 Paratroop Rifle Scope
	{
		torso raise_sniper
	}
}

activate
{
	default
	{
		torso open_door_1
	}
}

// dropweapon
// {
// 	weapons bazooka
// 	{
// 		torso reload_bazooka
// 	}
// }

reload
{
	weapons satchel charge
	{
		torso raise_medpack
	}
	// weapons Mortar AND Granatwerfer AND Mounted Mortar AND Mounted Granatwerfer
	// {
	// 	torso mortar_reload
	// }
	weapons smokeGrenade
	{
		torso raise_grenade
	}
	weapons Ammo Pack
	{
		torso raise_medpack
	}
	weapons Landmine
	{
		torso raise_grenade
	}
	weapons Satchel Charge
	{
		torso raise_medpack
	}
	weapons medicheal
	{
		torso raise_medpack
	}
	weapons special
	{
		torso raise_knife
	}
	weapons bazooka
	{
		NOOP
	}
	weapons panzerfaust
	{
		NOOP
	}
	weapons flamethrower
	{
		NOOP
	}
	// weapons Syringe AND Adrenaline Syringe
	// {
	// 	torso reload_syringe
	// }
	// weapons pistols, movetype idlecr
	// {
	// 	torso reload_pistol_cr
	// }
	weapons pistols, fast_reload
	{
		torso reload_pistol_fast
	}
	weapons pistols
	{
		torso reload_pistol
	}
	weapons akimbo_pistols, movetype idlecr
	{
		torso reload_akimbo
	}
	weapons akimbo_pistols
	{
		torso reload_akimbo
	}
	weapons Mobile MG 42 AND Mobile Browning
	{
		torso reload_mobilemg42
	}
	weapons Sten gun AND MP34, fast_reload
	{
		torso reload_sten_fast
	}
	weapons Sten gun AND MP34
	{
		torso reload_sten
	}
	weapons FG 42 Paratroop Rifle, fast_reload
	{
		torso reload_fg42_fast
	}
	weapons FG 42 Paratroop Rifle
	{
		torso reload_fg42
	}
	// weapons machineguns, movetype idlecr
	// {
	// 	torso reload_machinegun_cr
	// }
	weapons machineguns, fast_reload
	{
		torso reload_machinegun_fast
	}
	weapons machineguns
	{
		torso reload_machinegun
	}
// RIFLES
	weapons gpg40
	{
		NOOP
	}
	weapons M7
	{
		NOOP
	}
	weapons rifles
	{
		torso reload_rifle
	}
	// weapons Scoped M1 Garand
	// {
	//	torso reload_rifle
	// }
	// weapons K43 Rifle
	// {
	// 	torso reload_rifle
	// }
	// weapons m1 garand
	// {
	// 	torso reload_rifle
	// }
	// weapons Scoped K43 Rifle
	// {
	// 	torso reload_rifle
	// }
	// weapons K43 Rifle Scope
	// {
	// 	torso reload_rifle
	// }
	// weapons M1 Garand Scope
	// {
	// 	torso reload_rifle
	// }
	// weapons FG 42 Paratroop Rifle Scope
	// {
	// 	torso reload_rifle
	// }
}

jump
{
	// weapons none, movetype jumpforward
	// {
	// 	both jump_1step_1h
	// }
	// weapons none
	// {
	// 	both jump_nostep_1h
	// }
	// weapons rifles, movetype jumpforward
	// {
	// 	legs jump_1step_2h torso stand_srifle
	// 	// both jump_1step_fire_2h
	// 	// legs jump_1step_2h torso jump_1step_2h
	// }
	weapons satchel charge detonator, movetype jumpforward
	{
		legs jump_1step_1h
	}
	weapons satchel charge detonator
	{
		legs jump_nostep_1h
	}
	weapons Granatwerfer AND Mortar, movetype jumpforward
	{
		//legs stand_panzer torso e_mortar_stand
		//legs jump_1step_2h torso jump_1step_2h
		legs jump_1step_2h torso e_mortar_stand
	}
	weapons Granatwerfer AND Mortar
	{
		//legs jump_nostep_1h torso jump_1step_2h
		legs jump_nostep_1h torso e_mortar_stand
	}
	weapons one_handed_weapons, movetype jumpforward
	{
		//both jump_1step_1h
		legs jump_1step_1h torso stand_pistolB
	}
	weapons one_handed_weapons
	{
		//both jump_nostep_1h
		legs jump_nostep_1h torso stand_pistolB
	}
	weapons bazooka, movetype jumpforward
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons bazooka
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons panzerfaust, movetype jumpforward
	{
		legs jump_1step_2h torso stand_panzer
	}
	weapons panzerfaust
	{
		legs jump_nostep_1h torso stand_panzer
	}
	weapons scopes
	{
		legs jump_1step_1h
	}
	// TODO
	// weapons two_handed_weapons, movetype run, reloading
	// {
	// 	// legs jump_nostep_1h torso jump_1step_2h
	// 	// legs jump_nostep_1h torso stand_srifle
	// 	// legs jump_nostep_1h torso jump_1step_2h
	// 	legs jump_nostep_1h torso stand_mobilemg42
	// }

	// weapons Flamethrower, movetype jumpforward
	// {
	// 	both jump_1step_2h
	// }
	// weapons Flamethrower
	// {
	// 	// legs jump_nostep_1h torso jump_1step_2h
	// 	// legs jump_nostep_1h torso stand_srifle
	// 	// legs jump_nostep_1h torso both jump_nostep_1h
	// 	// both jump_nostep_1h
	// 	// both jump_1step_2h
	// 	legs jump_nostep_1h torso jump_1step_2h
	// }
	weapons two_handed_weapons, movetype jumpforward
	{
		// both jump_1step_fire_2h
		both jump_1step_2h
		// legs jump_1step_2h torso jump_1step_2h
	}
	weapons two_handed_weapons
	{
		legs jump_nostep_1h torso stand_machinegun
	}
	weapons dynamite weapon
	{
		both jump_1step_1h
	}
	gen_bitflag zooming
	{
		legs jump_1step_1h
	}
	firing
	{
		legs jump_1step_1h
	}
	weapons akimbo_pistols, movetype jumpforward
	{
		legs jump_1step_2h torso stand_akimbo
	}
	weapons akimbo_pistols
	{
		legs jump_nostep_1h torso stand_akimbo
	}
	// default
	// {
	// 	both jump_1step_1h
	// }
}

jumpbk
{
	weapons heavymgs
	{
		legs jump_nostep_1h torso stand_mobilemg42
	}
	weapons Granatwerfer AND Mortar
	{
		legs jump_nostep_1h torso e_mortar_stand
	}
	weapons satchel charge detonator
	{
		legs jump_nostep_1h
	}
	// weapons one_handed_weapons, movetype run, reloading
	// {
	// 	legs jump_1step_1h
	// }
	weapons one_handed_weapons, movetype run
	{
		//both jump_1step_1h
		legs jump_1step_1h torso stand_pistolB
	}
	// weapons one_handed_weapons, reloading
	// {
	// 	legs jump_nostep_1h
	// }
	weapons one_handed_weapons
	{
		//both jump_nostep_1h
		legs jump_nostep_1h torso stand_pistolB
	}
	weapons bazooka, movetype run
	{
		legs jump_1step_2h torso stand_rifle
	}
	weapons bazooka
	{
		legs jump_nostep_1h torso stand_rifle
	}
	weapons panzerfaust, movetype run
	{
		legs jump_1step_2h torso stand_panzer
	}
	weapons panzerfaust
	{
		legs jump_nostep_1h torso stand_panzer
	}
	weapons scopes
	{
		legs jump_1step_1h
	}
	// TODO
	// weapons two_handed_weapons, movetype run, reloading
	// {
	// 	legs jump_1step_2h
	// }

	weapons two_handed_weapons, movetype run
	{
		both jump_1step_2h
	}
	weapons two_handed_weapons
	{
		legs jump_nostep_1h torso stand_machinegun
	}
	// weapons two_handed_weapons, reloading
	// {
	// 	legs jump_nostep_1h
	// }
	// weapons two_handed_weapons
	// {
	// 	legs jump_nostep_1h torso stand_srifle
	// 	// both jump_nostep_1h
	// }
	weapons dynamite weapon
	{
		both jump_1step_1h
	}
	gen_bitflag zooming
	{
		legs jump_1step_1h
	}
	firing
	{
		legs jump_1step_1h
	}
	weapons machineguns
	{
		legs jump_nostep_1h torso stand_machinegun
	}
	weapons two_handed_weapons
	{
		// both jump_nostep_1h
		legs jump_nostep_1h torso stand_srifle
		// legs jump_nostep_1h torso jump_1step_2h
		// legs alert_crchidle_2h torso jump_1step_2h
	}
	weapons akimbo_pistols
	{
		legs jump_nostep_1h torso stand_akimbo
	}
	default
	{
		both jump_1step_1h
	}
}

climbdismount
{
	weapons scopes
	{
		legs climb_dis torso stand_rifle
	}
	weapons binoculars, gen_bitflag zooming
	{
		legs climb_dis torso stand_binoculars
	}
	weapons throwables, gen_bitflag holding
	{
		legs climb_dis torso holding_grenadeA
		legs climb_dis torso holding_grenadeB
	}
	default
	{
		legs climb_dis
	}
}

death
{
	movetype proning
	{
		both death_prone
	}
	movetype crouching
	{
		both death_crouch
	}
	default
	{
		both death_general
	}
}

revive
{
	default
	{
		both revive
	}
}

nopower
{
	default
	{
		torso e_no_juice
	}
}

pain
{
	impact_point legs
	{
		legs break_legs
	}
	movetype fallen
	{
		legs wounded_idle_1
	}
	movetype proning
	{
		legs prone_legs
	}
	movetype swimbk AND swim
	{
		legs e_swim_1h
	}
	movetype crouching, impact_point head
	{
		torso pain_cr_head
	}
	movetype crouching, impact_point shoulder_right
	{
		torso pain_cr_shoulderR
	}
	movetype crouching, impact_point shoulder_left
	{
		torso pain_cr_shoulderL
	}
	movetype crouching	// pick one at random if they failed
	{
		torso pain_cr_head
		torso pain_cr_shoulderR
		torso pain_cr_shoulderL
	}
	enemy_weapon flamethrower
	{
		torso pain_fire
	}
	stunned
	{
		torso pain_daze
	}
	impact_point head
	{
		torso pain_head
	}
	impact_point chest
	{
		torso pain_chest
	}
	impact_point gut
	{
		torso pain_gut
	}
	impact_point groin
	{
		torso pain_groin
	}
	impact_point shoulder_right
	{
		torso pain_shoulderR
	}
	impact_point shoulder_left
	{
		torso pain_shoulderL
	}
	impact_point knee_right
	{
	// legs ?
		torso pain_kneeR
	}
	impact_point knee_left
	{
	// legs ?
		torso pain_kneeL
	}
	default
	{
		torso pain_chest
		torso pain_gut
		torso pain_groin
	}
}

do_alt_weapon_mode
{
	weapons heavymgs
	{
		torso attach_mobilemg42
	}
	weapons rgrifles
	{
		torso attach_grenlauncher
	}
	weapons pistols
	{
		torso attach_silencer
	}
}

undo_alt_weapon_mode
{
	weapons heavymgs
	{
		torso detach_mobilemg42
	}
	weapons rgrifles
	{
		torso detach_grenlauncher
	}
	weapons pistols
	{
		torso detach_silencer
	}
}

do_alt_weapon_mode_prone
{
	weapons heavymgs
	{
		torso e_prone_heavymg_attach
	}
	weapons rgrifles
	{
		torso e_prone_rifle_attach
	}
	weapons pistols
	{
		torso e_prone_pistol_attach
	}
}

undo_alt_weapon_mode_prone
{
	weapons heavymgs
	{
		torso e_prone_heavymg_detach
	}
	weapons rgrifles
	{
		torso e_prone_rifle_detach
	}
	weapons pistols
	{
		torso e_prone_pistol_detach
	}
}

//==========================================================================
// CANNED_ANIMATIONS
//
//	These animations are played at random, momentarily cutting off the
//	above "normal" animations.
//
//	format:
//
//	(see ANIMATION section above)
//
//canned_animations

//==========================================================================
// STATECHANGES (Unused in Multiplayer)
//
// format:
//
// statechange <directionto> <state>
// {
//		[default / <condition type> [<condition value>], ...]
//		{
//			<both/legs/torso> <animation> [sound <filename>]
//			<both/legs/torso> <animation> [sound <filename>]
//			...
//		}
// }
//STATECHANGES
